modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="nexus"
displayName="Nexus"
version="${mod_version}"
logoFile="logo.png"
authors="Syconn"
updateJSONURL="https://raw.githubusercontent.com/Syconn/Nexus/master/updates.json"

description='''${mod_description}'''
[[dependencies.nexus]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.nexus]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"