modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="nexus"
displayName="Nexus"
version="0.1.0"
logoFile="logo.png"
authors="Syconn"

description='''${mod_description}'''
[[dependencies.nexus]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.nexus]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"